name: Delete hot-fix branch after merging/pushing to development branch

# Controls when the workflow will run
on:
  push:
    branches:
    - 'development'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Delete merged branch
    # from the github actions marketplace repo here: https://github.com/pabio/delete-merged-action
      uses: koj-co/delete-merged-action@master
      with:
      # only delete branches that start with 'hotfix' or 'hot-fix'
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
        branches: "hotfix*, 'hot-fix*'"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"