name: Delete feature branch after merge

# Controls when the workflow will run
on:
  pull_request:
    types: [ closed ]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Delete merged branch
    # from the github actions marketplace repo here: https://github.com/pabio/delete-merged-action
      uses: koj-co/delete-merged-action@master
      with:
      # do not delete master, development, or hot-fix-release branches
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
        branches: "!master, !development, !hot-fix*, *"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"