name: SCP Continuous Integration
on:
  push:
    branches:
      - development
      - master
  pull_request:

jobs:
  Run-All-Tests:
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install vault
        run: |
          sudo apt-get update && sudo apt-get -y install curl unzip jq
          sudo curl -O https://releases.hashicorp.com/vault/1.9.0/vault_1.9.0_linux_amd64.zip
          sudo unzip vault_1.9.0_linux_amd64.zip
          sudo mv vault /usr/local/bin
      - name: Load secrets and run tests
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          RAILS_LOG_TO_STDOUT: true
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
          CI: true
        run: |
          export VAULT_TOKEN=$( vault write -field=token auth/approle/login role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID )
          export DOCKER_IMAGE_TAG="$GITHUB_HEAD_REF-$GITHUB_SHA"
          docker build -t $DOCKER_IMAGE_TAG .
          docker images
          docker rim $DOCKER_IMAGE_TAG
          docker images
#          bin/load_env_secrets.sh -p secret/kdux/scp/staging/scp_config.json \
#                                  -s secret/kdux/scp/staging/scp_service_account.json \
#                                  -r secret/kdux/scp/staging/read_only_service_account.json \
#                                  -e test \
#                                  -n single-cell-portal-test
